/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import { Prisma, Institution } from "@prisma/client";

export class InstitutionServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count<T extends Prisma.InstitutionCountArgs>(
    args: Prisma.SelectSubset<T, Prisma.InstitutionCountArgs>
  ): Promise<number> {
    return this.prisma.institution.count(args);
  }

  async institutions<T extends Prisma.InstitutionFindManyArgs>(
    args: Prisma.SelectSubset<T, Prisma.InstitutionFindManyArgs>
  ): Promise<Institution[]> {
    return this.prisma.institution.findMany(args);
  }
  async institution<T extends Prisma.InstitutionFindUniqueArgs>(
    args: Prisma.SelectSubset<T, Prisma.InstitutionFindUniqueArgs>
  ): Promise<Institution | null> {
    return this.prisma.institution.findUnique(args);
  }
  async createInstitution<T extends Prisma.InstitutionCreateArgs>(
    args: Prisma.SelectSubset<T, Prisma.InstitutionCreateArgs>
  ): Promise<Institution> {
    return this.prisma.institution.create<T>(args);
  }
  async updateInstitution<T extends Prisma.InstitutionUpdateArgs>(
    args: Prisma.SelectSubset<T, Prisma.InstitutionUpdateArgs>
  ): Promise<Institution> {
    return this.prisma.institution.update<T>(args);
  }
  async deleteInstitution<T extends Prisma.InstitutionDeleteArgs>(
    args: Prisma.SelectSubset<T, Prisma.InstitutionDeleteArgs>
  ): Promise<Institution> {
    return this.prisma.institution.delete(args);
  }
}
